# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 5
  - name: News
    url: news
    weight: 10
  - name: In the Weeds
    url: post
    weight: 15
  - name: Bio
    url: author/christopher-m.-castille
    weight: 20
  - name: Research
    url: publication
    weight: 30
  - name: Assessments
    url: /assessments/library/
    weight: 35
  - name: Contact
    url: contact
    weight: 40
